name: CMake

on:
  push:
    paths:
    - ".github/workflows/**"
    - "external/**"
    - "game/**"
    - "include/**"
    - "src/**"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Recursively clone the repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup the build environment
      shell: bash
      run: mkdir -p $GITHUB_WORKSPACE/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
