name: docs

on:
  push:
    tags:
      - "*
    - name: Run Sphinx
      uses: sphinx-notes/pages@master
      with:
        documentation_path: "./doc"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        cname: thorn.gprb.me
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: "./doc/html"
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"
