name: Doxygen

on:
  push:
    paths:
    - ".github/workflows/doxygen.yml"
    - "include/**"
    - "src/**"

jobs:
  doxygen:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        enable-latex: false
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: "./doc/html"
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"
